#version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: bitpin
      POSTGRES_USER: bitpin
      POSTGRES_PASSWORD: bitpin
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network
    ports:
      - "5432:5432"

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app-network

  web:
    build: .
    command: >
      sh -c "
      python /app/wait_for_db.py &&
      cd /app/src &&
      python manage.py migrate &&
      python manage.py seed_db &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - ollama
    networks:
      - app-network
    environment:
      - DB_HOST=db
      - DB_NAME=bitpin
      - DB_USER=bitpin
      - DB_PASSWORD=bitpin
      - DB_PORT=5432
      - OLLAMA_URL=http://ollama:11434

volumes:
  postgres_data:
  ollama_data:

networks:
  app-network:
    driver: bridge